# AI Agent 3D Print System - Production Configuration
# This file contains production-specific overrides

app:
  environment: "production"
  debug: false
  log_level: "WARNING"

api:
  host: "0.0.0.0"  # Listen on all interfaces
  port: 8000
  workers: 4  # Multiple workers for production
  reload: false
  cors_origins:
    - "https://your-frontend-domain.com"
    - "https://your-app-domain.com"
  rate_limit:
    enabled: true
    requests_per_minute: 100  # Higher limit for production

database:
  echo: false
  url: "postgresql://username:password@localhost/ai_3d_print_prod"
  pool_size: 20
  max_overflow: 30

job_queue:
  type: "redis"  # Use Redis for production persistence
  redis_url: "redis://localhost:6379/0"
  max_retries: 5
  job_timeout: 600  # 10 minutes

agents:
  research:
    mock_mode: false
    web_research:
      cache_enabled: true
      cache_ttl: 3600  # 1 hour caching
      rate_limit: 10  # requests per minute
  
  cad:
    mock_mode: false
    
  slicer:
    mock_mode: false
    timeout: 300  # 5 minutes for complex models
    
  printer:
    mock_mode: false
    timeout: 1800  # 30 minutes for print operations

logging:
  level: "INFO"
  console_enabled: false  # Disable console logging in production
  file_enabled: true
  file_max_size: "50MB"
  file_backup_count: 10

security:
  api_key_enabled: true
  jwt_enabled: true
  jwt_secret: "${JWT_SECRET}"  # Use environment variable
  input_validation:
    sanitize_input: true
    max_text_length: 500

monitoring:
  health_check_enabled: true
  health_check_interval: 60
  metrics_enabled: true
  prometheus_enabled: true
  prometheus_port: 9090
  alerting:
    enabled: true
    webhook_url: "${ALERT_WEBHOOK_URL}"
    thresholds:
      memory_usage: 80  # percent
      cpu_usage: 85     # percent
      disk_usage: 90    # percent
      error_rate: 5     # errors per minute

cache:
  type: "redis"
  redis_url: "redis://localhost:6379/1"
  default_ttl: 7200  # 2 hours

# Production-specific features
production:
  backup:
    enabled: true
    schedule: "0 2 * * *"  # Daily at 2 AM
    retention_days: 30
  
  auto_scaling:
    enabled: true
    min_workers: 2
    max_workers: 8
    cpu_threshold: 70
  
  ssl:
    enabled: true
    cert_file: "/etc/ssl/certs/ai_3d_print.crt"
    key_file: "/etc/ssl/private/ai_3d_print.key"
